version: "3.8"

services:
  # -------------------------
  # 1) MySQL para Spring Boot
  # -------------------------
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306" 
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

  # -------------------------
  # 2) Spring Boot
  # -------------------------
  spring-service:
    build:
      context: ./calendario-api
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    depends_on:
      - mysql
      - express-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/calendario_festivo?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      # Si más adelante refactorizas tu código para usar esta variable:
      FESTIVOS_API_URL: http://express-service:3000/api/holidays
    networks:
      - backend

  # -------------------------
  # 3) MongoDB para Express
  # -------------------------
  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend

  # -------------------------
  # 4) Express + MongoDB
  # -------------------------
  express-service:
    build:
      context: ./festivos-api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://mongodb:27017/festivos
    networks:
      - backend

volumes:
  mysql-data:
  mongo-data:

networks:
  backend:
    driver: bridge
