version: "3.8"

services:
  # -------------------------
  # 1) MySQL para Spring Boot
  # -------------------------
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: calendario_festivo
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

  # -------------------------
  # 2) Spring Boot
  # -------------------------
  spring-service:
    build:
      context: ./calendario-api
      dockerfile: Dockerfile
    ports:
      - "8090:8090"   # expuesto para pruebas desde host
    depends_on:
      - mysql
      - express-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/calendario_festivo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      FESTIVOS_API_URL: http://express-service:3000/api/holidays
    networks:
      - backend

  # -------------------------
  # 3) MongoDB para Express
  # -------------------------
  mongodb:
    image: mongo:6

    volumes:
      - mongo-data:/data/db
    networks:
      - backend

  # -------------------------
  # 4) Express + MongoDB
  # -------------------------
  express-service:
    build:
      context: ./festivos-api
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://mongodb:27017/festivos
    networks:
      - backend

volumes:
  mysql-data:
  mongo-data:

networks:
  backend:
    driver: bridge
